name: local_ai_detection
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.4.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  camera: ^0.10.5+9
  

  permission_handler: ^11.1.0
  get_it: ^7.6.6
  image: ^4.1.4
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.7
  
  flutter_vision: ^1.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true
  

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/fonts/
    - assets/models/
    - assets/tessdata/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
          style: italic
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700